import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import {ThemeProvider} from "../components/theme-provider";
import {auth} from "../auth";
import {AuthProvider} from "../components/authProvider";
import {Toaster} from "sonner";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({children}: Readonly<{ children: React.ReactNode }>) {
    const session = await auth()

    return (
        <AuthProvider session={session}>
            <html lang="en" suppressHydrationWarning>
            <body className={inter.className}>
            <ThemeProvider
                attribute="class"
                defaultTheme="light"
                enableSystem
                disableTransitionOnChange
            >{children}
                <Toaster/>
            </ThemeProvider>
            </body>
            </html>
        </AuthProvider>
    );
}
